#ifndef MODEL_H
#define MODEL_H

// This file may be auto-generated by `model/convert_tflite_to_c.py`.
// After generating, compile the produced `.cc` alongside the firmware so the
// linker provides `edgemind_model` and `edgemind_model_len` symbols.

extern unsigned char edgemind_model[];
extern unsigned int edgemind_model_len;

#endif // MODEL_H
